### ISSUE TITLE
fn modifier

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/khd#11]

**Comment by koekeishiya** [comment]
the following is a list of keys that is not properly working with the fn modifier, for unknown reasons.

```
fn - return
fn - backspace
```

**Comment by dominiklohmann** [comment]
`fn - backspace` is the `delete` key on mac keyboards and `fn - return` is `enter`. Pretty sure you can't override these.

**Comment by koekeishiya** [comment]
Caused weird issues again so I'm gonna be removing these changes.

**Comment by net** [comment]
@koekeishiya `fn - <key>` doesn't work for me. I've tried it with several letters.

**Comment by net** [comment]
Oops, missed your last reply.

I would really like to see this modifier. Should I open a new issue, or have you decided not to implement it?

**Comment by koekeishiya** [comment]
> I would really like to see this modifier. Should I open a new issue, or have you decided not to implement it?

I never managed to figure out why it seems to break other functionality, so for now, no plans.

Sorry!

**Comment by net** [comment]
@koekeishiya what did it break? I just reimplemented [48d8030](https://github.com/koekeishiya/khd/commit/48d803013cce2a6178547c3886cda5b37b4452fb) and it seems to work fine.

**Comment by koekeishiya** [comment]
I don't remember exactly, but this was the 2nd attempt and it still broke.
First time was when Kwm had a keybinding systme.
Ref: https://github.com/koekeishiya/kwm/issues/288

**Comment by net** [comment]
Well, if I find something broken with the `fn` modifier enabled I'll document it here, but thus far everything seems working.
