### ISSUE TITLE
Migrating kwm binds to khd?

### ISSUE THREAD

**Issue by vendion** [koekeishiya/khd#12]
If I understand `khd` is the replacing the keybinding support that use to be baked into `kwm` if so is there a way to migrate (either documented or a tool that will do that automatically) the old _binds_ file from `kwm` or will we need to start from scratch config wise?

**Comment by koekeishiya** [comment]
The syntax is very similar, so it should not be hard to migrate existing binds manually.

It is possible to use the parsing code in Kwm to read the old bind format into the datastructure (identical between both Kwm and Khd), and from there output it in the format which Khd expects. 

I do not have time to make this tool, however, both projects are MIT Licensed, so anyone can do this if they'd like.

**Comment by koekeishiya** [comment]
I don't really think this is necessary to do at this point.
Closing.
