### ISSUE TITLE
Command not found with zsh

### ISSUE THREAD

**Issue by therockmandolinist** [koekeishiya/khd#14]
OSX version: 10.12 (Sierra)
Khd: 1.1.0

Keybindings are not working, and my `khd.err` file contains a lot of this:

```
zsh:2: command not found: khd
zsh:1: command not found: kwmc
```

`$SHELL` is set to `/usr/local/bin/zsh`, and the commands do work when I run them from the command line in iTerm with `$SHELL -c "kwmc tree rotate 90"`, for example.

I know this is little information, but I'm not quite sure how to proceed.

**Comment by koekeishiya** [comment]
See #9
