### ISSUE TITLE
Press events get lost?

### ISSUE THREAD

**Issue by choco** [koekeishiya/khd#15]
I don't know why but press doesn't always work. To easily test just setup a mapping to move between spaces for example:

```
ctrl + alt - right      :   khd -p "ctrl - right"
ctrl + alt - left      :   khd -p "ctrl - left"
```

and after 2-3 presses you should see that the press isn't working

**Comment by koekeishiya** [comment]
Can confirm this issue.

Weird thing is that it is not consistent with other press stuff.
e.g: khd -p "shift + alt - 8" is spammable

The code is the exact same as was in Kwm for this purpose, so I don't really know why that would become a proble now.

**Comment by cHoco** [comment]
Using CGPostKeyboardEvent deprecated API works and doesn't hang after a few presses, if only Apple documented how to correctly use the new ones and didn't fill them with bugs....
```
CGPostKeyboardEvent( (CGCharCode)0, (CGKeyCode)0x3B, true );
if(alt) {
    CGPostKeyboardEvent( (CGCharCode)0, (CGKeyCode)124, true );
    CGPostKeyboardEvent( (CGCharCode)0, (CGKeyCode)124, false );
    alt = false;
} else {
    CGPostKeyboardEvent( (CGCharCode)0, (CGKeyCode)123, true );
    CGPostKeyboardEvent( (CGCharCode)0, (CGKeyCode)123, false );
    alt = true;
}
CGPostKeyboardEvent( (CGCharCode)0, (CGKeyCode)0x3B, false );
```

**Comment by mnetzwur** [comment]
The cursor keys didn't work for me with the latest 3.1 version either after upgrading to Sierra. However, with khd, a whole range of other key combinations don't work (that do indeed work with kwm). For example khd -p cmd+shift-b does not work while kwmc press cmd+shift-b does not.

**Comment by choco** [comment]
Today I upgraded to Sierra and CGPostKeyboardEvent was removed, and khd -p "ctrl - right" just doesn't work :( I think this may be a similar issue that affected karabiner :(

**Comment by choco** [comment]
Ok I had time to take a look at karabiner and see how the author approached the problem and was able to get it working, I'll try to come up with a pull request in the weekend.

**Comment by koekeishiya** [comment]
@choco Are you sure step 1. is necessary?

Inserting time intervals between CGPostEvents seem to do the trick for me.
I am still running El Capitan, so maybe step 1. is only necessary on Sierra?

**Comment by choco** [comment]
@koekeishiya Sorry for not working/updating status on this, never really had time. You're right, step one isn't necessary; you can freely remove the press and release modifier call if you want. But at least on Sierra it's necessary to preserve key event flags for it to work. Opened https://github.com/koekeishiya/khd/pull/40 to fix it

**Comment by koekeishiya** [comment]
@choco #81 appears to be this problem?

**Comment by koekeishiya** [comment]
@choco 
```
    CGPostKeyboardEvent( (CGCharCode)0, (CGKeyCode)124, true );
    CGPostKeyboardEvent( (CGCharCode)0, (CGKeyCode)124, false );
```

This works just fine on High Sierra (10.13.2).

**Comment by choco** [comment]
Did they add back the symbols for `CGPostKeyboardEvent`? It would make sense since `CGEventPost` is sooooo buggy (I personally hate timing hacks wtf), or at least they should document how to use it reliably since each macOS revision seems to change the behaviour.

**Comment by koekeishiya** [comment]
Started working a bit on https://github.com/koekeishiya/qes and had the same idiotic problem with `CGEventPost` so figured I'd try the ones you mentioned here for the heck of it, and they actually work just fine :)
