### ISSUE TITLE
Can't get khd to work with kwm

### ISSUE THREAD

**Issue by simonsmith** [koekeishiya/khd#16]
Hey,

I'm running `kwm` (4.0.2) and `khd`  (1.1.0). I've added both example `kwmc` and `khdrc` files from the KWM [example directory](https://github.com/koekeishiya/kwm/tree/master/examples) to the relevant places. KWM works as expected but hotkeys do not work.

I've given permission to both applications in my accessibility settings, on Mac OS X ElCapitan (10.11.6).

Both services are running in `brew services list` but interestingly if I try to interact with `khd` it says `Khd: Could not start daemon! Terminating.`

It does seem to intercept some keys though as pressing cmd+enter to fullscreen iTerm doesn't work whilst khd is running.

Anything I've missed?

**Comment by koekeishiya** [comment]
Probably #9 

You can check log files to confirm:
```
tail -f /tmp/khd.err
```

**Comment by simonsmith** [comment]
Thanks,

Error was `kwm` couldn't be found. `sudo launchctl config user path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` fixed it.
