### ISSUE TITLE
Khd not working 

### ISSUE THREAD

**Issue by antmbel** [koekeishiya/khd#17]
So I installed khd and copied the example config using the command 

> cp /usr/local/Cellar/khd/1.1.0/khdrc ~/.khdrc

I then used the command 

> khd

And it outputted 

> Khd: Could not start daemon! Terminating.

I then used the commmand 

> tail -f /tmp/khd.err

and it just hung there forcing me to use control+c to quit. Am I doing something wrong here? None of my KWM binds are working and khd seems to not be working at all... Earlier I could get the error report and it said 

> Khd: Could not open file '~/.khdrc'

This I thought was weird because the file is there... Thanks for the help

Edit: I forgot to mention this is after I started both services using brew services start kwm/khd

**Comment by internaught** [comment]
Same here and I have homebrew installed to my homefolder:

> Khd: Could not start daemon! Terminating.

**Comment by dominiklohmann** [comment]
@internaught you shouldn't use `brew` with `sudo`. Also, what's the output of `brew doctor`?

**Comment by antmbel** [comment]
Brew doctor says everything is fine for me

**Comment by internaught** [comment]
```
14:39 $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/cabrinha/stash/wulfcli/src/bin/test-config
  /Users/cabrinha/stash/wulfcli/src/bin/wnl-vault-config

Warning: A .pydistutils.cfg file was found in $HOME, which may cause Python
builds to fail. See:
  https://bugs.python.org/issue6138
  https://bugs.python.org/issue4655

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libnvpair.1.dylib
  /usr/local/lib/libuutil.1.dylib
  /usr/local/lib/libzfs.2.dylib
  /usr/local/lib/libzfs_core.1.dylib
  /usr/local/lib/libzpool.1.dylib

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libnvpair.la
  /usr/local/lib/libuutil.la
  /usr/local/lib/libzfs.la
  /usr/local/lib/libzfs_core.la
  /usr/local/lib/libzpool.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libnvpair.a
  /usr/local/lib/libuutil.a
  /usr/local/lib/libzfs.a
  /usr/local/lib/libzfs_core.a
  /usr/local/lib/libzpool.a

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
```

**Comment by koekeishiya** [comment]
>  I forgot to mention this is after I started both services using brew services start kwm/khd

doing `brew services start khd` will cause brew to start Khd. 

> I then used the command
 khd

This will indeed not run because the instance started by brew locks the port 3021.

> I then used the commmand

>    tail -f /tmp/khd.err

> and it just hung there forcing me to use control+c to quit.

This is the expected behaviour of tail with the -f argument. You can use other tools such as `cat` if you want to see the entire contents of the file.

Do notice that the example khdrc file in this repository has no connection to the example Kwm config.

You should be able to run Khd manually by doing the following:
```
brew services stop koekeishiya/khd/khd
khd
```

If that doesn't work, make sure nothing is blocking port 3021:
```
lsof -i :3021
```

**Comment by internaught** [comment]
```
😎  ~
14:53 $ brew services stop koekeishiya/khd/khd
Error: Service `khd` is not started.
🤕  ~
14:53 $ khd
Khd: Could not start daemon! Terminating.
🤕  ~
14:53 $ lsof -i :3021
🤕  ~
14:53 $
```

**Comment by koekeishiya** [comment]
> 😎  ~
14:53 $ brew services stop koekeishiya/khd/khd
Error: Service `khd` is not started.
🤕  ~
14:53 $ khd
Khd: Could not start daemon! Terminating.
🤕  ~
14:53 $ lsof -i :3021
🤕  ~
14:53 $

Should probably be fixed after a reboot, seems like some table is messed up, never had anything like that happen to me.

Basically, in your case this function returns false because one of the following system calls fail:
```
socket()
bind()
listen()
``` 

Relevant code [here](https://github.com/koekeishiya/khd/blob/master/src/daemon.cpp#L102)

**Comment by antmbel** [comment]
My problem was solved. My keybinds were messed up in the .khdrc file leading me to believe that I had messed something else up... Ill leave this issue open until internaught confirms his problem was fixed after a reboot. Thank you for your patience.

**Comment by internaught** [comment]
Rebooting isn't really a "fix" for the issue. Brew services isn't starting khd. Why? I can get khd running by manually pointing it at the config file and spawning a new terminal window. Not ideal in the least. Can I just go back to a previous version of KWM where KHD wasn't a thing yet?

**Comment by dominiklohmann** [comment]
To be honest, this doesn't sound like the issue lies within khd. It much rather sounds like your Homebrew messed up there.

Have you tried removing and then reinstalling khd through brew?

**Comment by internaught** [comment]
I think the issue has to do with:

02:41 $ cat homebrew.mxcl.khd.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>homebrew.mxcl.khd</string>
  <key>ProgramArguments</key>
  <array>
  <string>/Users/cabrinha/homebrew/bin/khd</string>
  </array>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/khd.out</string>
  <key>StandardErrorPath</key>
  <string>/tmp/khd.err</string>
  <key>Sockets</key>
  <dict>
    <key>Listeners</key>
    <dict>
      <key>SockServiceName</key>
      <string>3021</string>
      <key>SockType</key>
      <string>dgram</string>
      <key>SockFamily</key>
      <string>IPv4</string>
  </dict>
</dict>
</dict>
</plist>
```

**Comment by koekeishiya** [comment]
> "ProgramArguments" has the string hard coded to /usr/local/bin on the initial install.

Fixed.

> I have a feeling that something else is hardcoded around that path as well, because there has been talk of $PATH being incorrectly set by various shells like zsh and fish. 

This is because launchd has its own environment settings.

**Comment by therockmandolinist** [comment]
I'm actually having this same issue now. I've tried uninstalling, rebooting, and reinstalling but I can't seem to get it to work. One time it did, though I'm not sure what I did, but it stopped again as soon as I hit the keys for switcher mode.
