### ISSUE TITLE
Help with config

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/khd#19]
So i just converted my binds over from kwm, and i'm getting 'Expected token of type 'Token_Command' after symbols!'. Not sure why.

Here's my khdrc. Any help appreciated.
https://gist.github.com/anonymous/5723e328967c91f3b2e93374c5223c56

**Comment by koekeishiya** [comment]
I don't think `,` and `.` are valid anymore. You need to specify these using the keycode.

See #1 for how to figure out the keycode you need.

**Comment by matthewdias** [comment]
thanks!
