### ISSUE TITLE
Remap modifier state

### ISSUE THREAD

**Issue by webgefrickel** [koekeishiya/khd#21]
Hi there! I've wondered if it is possible to "remap" modifier keys, basically to replicate two features for which I have for now installed Seil/Karabiner:
- when I press+hold the left alt key, 'it' actually emits cmd+ctrl+alt+shift. This way I kind of create a hyper-key for key combination no app uses. I for example use this to start Alfred with cmd+ctrl+alt+shift - space — but when I try to remap this in khd, it only works once, and even does so when run directly from the command line with `khd -p "cmd+ctrl+alt+shift - space"`. Do you have any idea how I could get around this issue?
- when I press the left alt key for a short period (and do not hold it) it actually emits 'esc' — as I unterstand it, this should be possible with this config

```
khd mod_trigger_timeout 0.25
lalt : khd -p "esc"
```

But this too does not work... I would really appreciate some help on this. After all, Seil/Karabiner still work, but if I could do without those, why not? ;)

(OSX 10.11.6, khd 1.1.0)

**Comment by koekeishiya** [comment]
Uh, `lalt : khd -p "- esc"` should work.
The key literals require a `-` in front due to a parsing ambiguity.

If you use the keycode instead, this problem does not occurr.

**Comment by webgefrickel** [comment]
Thank you so much! The trick with the literal did work :)
Do you have any idea regarding the issue with triggering a global shortcut involving all modifier keys?

**Comment by koekeishiya** [comment]
> when I press+hold the left alt key, 'it' actually emits cmd+ctrl+alt+shift. This way I kind of create a hyper-key for key combination no app uses. I for example use this to start Alfred with cmd+ctrl+alt+shift - space — but when I try to remap this in khd, it only works once, and even does so when run directly from the command line with khd -p "cmd+ctrl+alt+shift - space". Do you have any idea how I could get around this issue?

This is not actually supported by Khd, as it doesn't modify the modifier flags set for incoming keyevents. It only detects whether a modifier was pressed and tries to match that modifier with some predefined binding.

What you want to do, would require actually remapping the state of modifiers for incoming keyevents.

As in your exanple, holding Alt when a keyevent is received, would yield roughly the following event structure (true means modifier is set, false means it is not):
```
cmd: false
alt: true
shift: false
ctrl: false
```

So what seil/karabiner basicaly does is changing it to be (in your example) the following:
```
cmd: true
alt: true
shift: true
ctrl: true
```

So when it processes the key, it actually has all the correct modifier flags as well.

This is not true for Khd, but I believe it should be possible to implement in a future version, if there is enough demand for it.

**Comment by webgefrickel** [comment]
Thanks a lot for your elaborate answer! So for now I will still use Seil/Karabiner to achieve this, but if you find the time (and more requests for such a special feature) I would be very happy about this.

Nonetheless: I've just migrated everything to khd/kwm4 and I am very happy with my current setup. Thank you so much. This really boosts productivity!

**Comment by diiq** [comment]
Seconding the request to simulate modifier keys!

In previous versions of OSX I was able to have:
`enter : enter`   (tap once for enter)
`enter + [any key] : Ctrl + [any key]` (chord with another key for ctrl)

And ditto with Capslock -- it acted both as `esc` AND `command`.

But seil and karabiner don't work with Sierra -- and the new Karabiner Elements can't emulate modifier keys, either -- so I'm stuck. khd seems the closest to recreating this goal.

**Comment by LnL7** [comment]
The capslock usecase should work properly with my changes.
I have my capslock remapped to ctrl in the keyboard preferences and use this:

```
khd mod_trigger_timeout 0.2
lctrl    :   khd -p "0x35"
```

**Comment by koekeishiya** [comment]
I've decided this is out of scope for Khd, see #50
