### ISSUE TITLE
Hotkey response time is slower in 1.1.0

### ISSUE THREAD

**Issue by kconner** [koekeishiya/khd#23]
When I type a hotkey, khd 1.1.0 takes a long time to perform its action. In 1.0.1, hotkeys took effect immediately. I reproduce this on two machines running Sierra.

For instance, my left command + O is bound to simulate the left arrow key. When I press and hold those keys, I expect my text editor's insertion point to move at the key repeat rate, just like if I held the left arrow key. But while I hold the keys, I see slow and staggered motion.

I can even type a hotkey, then immediately hit another key that is not a hotkey, and the second key will take effect before the hotkey does.

My config: https://gist.github.com/kconner/9c7d3c89d187e091a65b67ec398c5e0a

**Comment by braham-snyder** [comment]
Same issue here on El Capitan--don't know when exactly it started, but definitely within the last week. Happens with the default configuration as well. Even, e.g., the example config's `cmd - 8` for `khd -w "{"` exhibits this significant delay. The delay is consistently about a second or a bit less, for every khd command. As noted above, keypresses during the delay can be lost: e.g., entering a window-resizing mode and pressing `h` to increase the window size to the west will bypass khd if `h` is pressed during the delay and `h` was not bound in the prior mode. `khd.err` contains no errors. And nothing in `khd.out` jumps out at me.

That being said, I tried to rollback to 1.0.1 to test for the delay, but ran into some kind of path error. `khd.err` was full of:
```
/bin/bash: khd: command not found
/bin/bash: kwmc: command not found
```

**Comment by nanzhong** [comment]
I can confirm that I have the same issue on Sierra.

**Comment by blissdev** [comment]
I seem to be at least getting the command not found errors that @braham-snyder mentioned in Sierra.

**Comment by jackwakefield** [comment]
I've been having the same issue since updating to Sierra a month or so ago. I've just removed Homebrew and moved to MacPorts, I'm yet to figure out why but response times are suddenly 2-3x times quicker.

**Comment by braham-snyder** [comment]
Got a chance to get 1.0.1 working again--it does not exhibit this key delay for me either.

For those looking to temporarily downgrade to 1.0.1:

```
brew unlink khd
brew install https://github.com/koekeishiya/homebrew-khd/raw/06750f0876fea87ea2f9905f4370bbcd837c91ac/khd.rb  # url for khd v1.0.1 formula
```

You can easily switch later using `brew switch`.

 @blissdev for those path errors, see issue #9--and perhaps note that, elsewhere, someone mentioned that homebrew services was overwriting their manually-edited plist file (though there are other, easier ways to circumvent the problem, mentioned in #9):

> Edit/Update: Ah, and if you're using brew services to start and stop it, it will overwrite the plist so you need to update the plist file in homebrew!

**Comment by blissdev** [comment]
@braham-snyder Thanks, I got it working by manually updating the path for the service.

**Comment by koekeishiya** [comment]
Uh, I'm unable to reproduce this on my machine at this moment using the config provided by @kconner. The speed is the same when running on version `1.1.0` and `1.0.1`.

@braham-snyder 
> Even, e.g., the example config's cmd - 8 for khd -w "{" exhibits this significant delay.

I did run into this a long time ago, but has since not been able to reproduce the problem.
Any additional information regarding this issue would be great.

Note: I am still running El Capitan 10.11.6

**Comment by willhoag** [comment]
@koekeishiya I downgraded to 1.0.1 and that solved my problem. I'm running OS Sierra 10.12.2.

I'm not sure if I changed anything in my current config to get 1.0.1 set up, but here it is:
.khdrc - https://www.pastiebin.com/586c8a3766079
.kwm/kwmrc - https://www.pastiebin.com/586c8b3b61c2d

**Comment by braham-snyder** [comment]
I think it's 643ac20ff238e744b8f06bb3e58b2cd33f56f4d5 combined with fish -- when `$SHELL` is fish, I see the delay, when `$SHELL` is anything else, I don't

**Comment by dominiklohmann** [comment]
How long does it take you do launch an instance of `$SHELL`?  
You should be able to roughly test that with `time $SHELL -c exit`.

**Comment by braham-snyder** [comment]
@dominiklohmann thanks! I'd wondered when I'd have to actually worry about the distinction between non- and login/interactive shells. In my particular case, `source (conda info --root)/etc/fish/conf.d/conda.fish` in my `config.fish` was the main offender. `if status --is-interactive` around it was all I needed.

**Comment by koekeishiya** [comment]
I still can't reproduce this on my end. 
Is this confirmed to be caused by users shell config (#10) and not directly related to Khd?

The only other changes that I remember between 1.0.1 and 1.1.0 (except for #10), is the addition of modifier only binds. I just want to make sure before any future changes are made to the codebase, that this is in fact not caused by modifier only bindings.

**Comment by koekeishiya** [comment]
I'm gonna consider this issue resolved, given the new information in the previous posts.
I'm also unable to reproduce this issue on my end.

**Comment by kconner** [comment]
I confirm that switching my Mac OS user account shell from `/usr/local/bin/fish` to its default, `/bin/bash`, fixed slow hotkey response times. Indeed the amount of time it takes to open a new Terminal tab is about the same as the hotkey response time I was seeing.

Is there a way I can configure the `khd` service with `brew` to use a `$SHELL` that I specify? I'd like to keep using fish in the terminal and bash as my user.

For now I'm configuring the Terminal app to use `fish` and leaving my system default shell as `bash`. Maybe that will be fine.

**Comment by dominiklohmann** [comment]
Assuming you installed via Homebrew.

Stop running it via Homebrew.
```
brew services stop khd
```

Save this file as a `.plist` in `$HOME/Library/LaunchAgents/`.
```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>homebrew.mxcl.khd</string>
  <key>ProgramArguments</key>
  <array>
  <string>/usr/local/Cellar/khd/2.0.0/bin/khd</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
      <key>PATH</key>
      <string>$PATH:/usr/local/Cellar/khd/2.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
      <key>SHELL</key>
      <string>/bin/bash</string>
  </dict>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/khd.out</string>
  <key>StandardErrorPath</key>
  <string>/tmp/khd.err</string>
  <key>Sockets</key>
  <dict>
    <key>Listeners</key>
    <dict>
      <key>SockServiceName</key>
      <string>3021</string>
      <key>SockType</key>
      <string>dgram</string>
      <key>SockFamily</key>
      <string>IPv4</string>
  </dict>
</dict>
</dict>
</plist>
```

Make it load on login via `launchctl`.
```
launchctl load $HOME/Library/LaunchAgents/<filename>.plist
```

When updating Khd you will have to manually update the path to the Khd binary.

Alternatively you can configure launchctl to always have `SHELL=/bin/bash` set, but that might mess up other applications.

**Comment by benjaminwood** [comment]
I can confirm this problem, and also the workaround. When login shell is zsh, khd is super slow (like 1 second + to respond). When I switch my login shell to bash, khd is as snappy as I expect it to be.

zsh in itself may not be the problem. I'm also using oh-my-zsh with extensions/plugins, so one of those could be the cause. For now, I'm going to follow @dominiklohmann's advice and create a custom LaunchAgent.

@koekeishiya can this issue be re-opened? I'm happy to help debug by sharing my zsh config, etc.

**Comment by Noah-Huppert** [comment]
I ran into this issue on High Sierra after I installed khd. 

I tried all the solutions listed in this thread but none solved the issue. I eventually uninstalled khd and the problem persisted. This led me to believe that the problem was actually a OS problem, not a khd problem.  

## Solution
Open System Preferences > Keyboard > Keyboard Tab and adjust:

- "Key Repeat" to "Fast" (Far right)
- "Delay Until Repeat" to "Short" (Far right).  

This solved the issue. I believe installing khd might have tweaked these issues without me knowing.
