### ISSUE TITLE
Is it possible to map a command to move left/right a space?

### ISSUE THREAD

**Issue by MaiaVictor** [koekeishiya/khd#28]
I'm aware I can do this on OSX settings, but I would like a command to simultaneously move a kwm window right, and to go to the right space. Is that possible?

**Comment by chrishoage** [comment]
In the example config you can find this example:

```
switcher + shift - z    :   kwmc window -m space left;\
                            kwmc space -fExperimental left
```

The `;` allows multiple commands to be run sequentially. This command sequence moves a window to the left, then focuses the space to the left using the "experimental" kwmc space switcher that skips the space moving animation. 

If you would like to retain the space animation you can tell `khd` to issue the key combination you have bound in your OS X settings like so `khd -p "cmd + alt - left"` (this assumes that `cmd + alt - left` is the key press you use to move to the space to the left.
