### ISSUE TITLE
Sending control characters

### ISSUE THREAD

**Issue by Stiivi** [koekeishiya/khd#29]
How is it possible to send control characters such as `^W` (for vim) or `^B` (for tmux) followed by a sequence of other characters? For example I would like to map: `ctrl + cmd - /` to `^B` followed by `z`

**Comment by therealmarv** [comment]
Concatenate the command with `|`  and it should be this one if I can read it right: 

```
ctrl + cmd - /     :   khd -p "ctrl + shift - b" | khd -w "z"
```

**Comment by koekeishiya** [comment]
You need to use the keycode to find ```/```. See issue #1
Then replace 0x1E below with your keycode.

```
ctrl + cmd - 0x1E : khd -p "ctrl - b"; khd -p "- z"
```
