### ISSUE TITLE
Allow just modifiers

### ISSUE THREAD

**Issue by 0x3333** [koekeishiya/khd#3]
I'd like to be able to create the follow binding:

`cmd + cmd : khd -p "cmd + alt + shift - a"`

Pressing `cmd` 2 times would simulate a `cmd + alt + shift -a` key press.

AFAIK this is not possible.

**Comment by koekeishiya** [comment]
A modifier press alone does not generate an event, and so that is not possible to do with the [Quartz Event Services](https://developer.apple.com/reference/coregraphics/1658572-quartz_event_services?language=objc) that Khd uses.

You could maybe achieve something like you mentioned by using Karabiner / Seil.

**Comment by 0x3333** [comment]
Right, I used to do this using Karabiner, but it isn't working in Sierra release. I just got to your project from a Karabiner issue.

Thanks anyway.

**Comment by dominiklohmann** [comment]
There's a WIP rework of Karabiner for Sierra https://github.com/tekezo/Karabiner-Elements

**Comment by 0x3333** [comment]
Right, but it doesnt have support for doubl press. 

I'll have to wait...

Thanks

**Comment by dominiklohmann** [comment]
> Right, but it doesnt have support for doubl press.

Should khd ever get support for modifier key only events, you can get the double press functionality by making the first press enter a mode and the next press (if in the mode) activate whatever you want the double press to do. So support for that kinda is already there.

**Comment by 0x3333** [comment]
I don't believe it is possible, as only modifier is not supported in khd.

> koekeishiya:
> A modifier press alone does not generate an event, and so that is not possible to do with the Quartz Event Services that Khd uses.

**Comment by koekeishiya** [comment]
See #6
