### ISSUE TITLE
Support for sticky keys?

### ISSUE THREAD

**Issue by gallimatias** [koekeishiya/khd#30]
Does khd support sticky keys? It would be nice for examle to make Preview.app emulate the vim keybinding: press "g", then release, and then press "g" again to jump to the top of a document. I would then also be able to access the "Go to page"-feature by mnemonic mapping: "g" release, then "t".

**Comment by dominiklohmann** [comment]
You should be able to do this by creating modes.  

This is an example mode named `fancyname`
```
khd mode fancyname prefix on
khd mode fancyname restore default
khd mode fancyname timeout 0.75
```

Pressing `g` activates the mode `fancyname`
```
g : khd -e "mode activate fancyname"
```

Pressing `g` while in mode `fancyname` runs whatever you want (a script that scrolls up?)
```
fancyname - g : osascript scrolltotop.applescript
```

You can also make this work while only in Preview.app
```
fancyname - g [ Preview ] : osascript scrolltotop.applescript
```

**Comment by gallimatias** [comment]
Thanks! I take it that I have to write that applescript myself?

**Comment by dominiklohmann** [comment]
You can have it execute whatever you want, it doesn't necessarily have to be applescript. I just don't know of any other ways to do GUI scripting in macOS aside from it.

For what you're trying to do you could probably just make it simulate a "Home" key press, which is equivalent to Keycode 115 or `fn - left`.
