### ISSUE TITLE
Help setting up khd

### ISSUE THREAD

**Issue by jesusvazquez** [koekeishiya/khd#31]
Hi, 

I'm new with both kwm and khd, as of today I installed the latest versions available in github.
```
$ brew install koekeishiya/kwm/kwm
Warning: koekeishiya/kwm/kwm-4.0.2 already installed
$ brew install koekeishiya/khd/khd
Warning: koekeishiya/khd/khd-1.1.0 already installed
```
I granted both accesibility rights in the security panel.  Kwm seems to be working fine, it resizes the windows automatically and the focus follows my mouse (really nice!).

Now when I installed khd I also run the command ```cp /usr/local/Cellar/khd/1.1.0/khdrc .khdrc```, then I started the khd service:
```
$ brew services start khd
==> Successfully started `khd` (label: homebrew.mxcl.khd)
$ khd
Khd: Could not start daemon! Terminating.
```
Then I tried a couple of the commands listed in the README.md:

 - ``$ khd -e "mode activate default"`` does nothing and outputs the following in the */tmp/khd.err*: ``zsh:1: command not found: kwmc``
 - Others that seem to be working:
```
$ khd -w "this text will be printed by generating key-up/down events"
this t%                                                       
$ this text will be printed by generating key-up/down events
$ khd -p "cmd - right"
Token_Modifier: cmd
Token_Literal: right
```

So following with the issue #25 I tried the following configuration:
```
# Change focus
lalt - up : kwmc window -f north
lalt - right : kwmc window -f east
lalt - down : kwmc window -f south
lalt - left : kwmc window -f west

# Move window
lalt + shift - up : kwmc window -m north
lalt + shift - right : kwmc window -m east
lalt + shift - down : kwmc window -m south
lalt + shift - left : kwmc window -m west

# Open iterm
lalt - return : open -na /Applications/iTerm2.app
```

And restarted the service with the same outcome: 
```
$ brew services restart khd
Stopping `khd`... (might take a while)
==> Successfully stopped `khd` (label: homebrew.mxcl.khd)
==> Successfully started `khd` (label: homebrew.mxcl.khd)
$ khd
Khd: Could not start daemon! Terminating.
$ khd -c .khdrc
Khd: Could not start daemon! Terminating
```

Don't know what I'm missing but I would really like to make it work! Some help would be appreciated. 

Cheers

**Comment by koekeishiya** [comment]
Seems like path issues, see #9 

> $ brew services restart khd
Stopping `khd`... (might take a while)
==> Successfully stopped `khd` (label: homebrew.mxcl.khd)
==> Successfully started `khd` (label: homebrew.mxcl.khd)
$ khd
Khd: Could not start daemon! Terminating.
$ khd -c .khdrc
Khd: Could not start daemon! Terminating

brew services starts khd for you, so trying to manually run it afterwards will not work as the port will already be in use.

**Comment by jesusvazquez** [comment]
@koekeishiya that makes it work. I wonder why this happens since /usr/local/bin/kwmc is in my path...

Thank you! And really good job, for those who come from linux you are making us happy.

Cheers
