### ISSUE TITLE
sxhkd style substitutions 

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/khd#32]
Over the weekend I installed bspwm and sxhkd in a virtual machine and had a pretty cool experience. 

There are quite a few features that sxhkd has that it it would be cool if khd has. Chords would be neat but go against how modes work. 

One that I think would fit right in is the way they do substitutions. 

For example:

```
manage - left             : kwmc space -p increase left
manage - right            : kwmc space -p increase right
manage - up               : kwmc space -p increase top
manage - down             : kwmc space -p increase bottom
manage + shift - left     : kwmc space -p decrease left
manage + shift - right    : kwmc space -p decrease right
manage + shift - up       : kwmc space -p decrease top
manage + shift - down     : kwmc space -p decrease bottom
```

Becomes:

```
manage {_,+ shift} - {left, right, up, down} : \
  kwmc space -p {increase, decrease} {left, right, top, bottom}
```

It could remove a lot of the repetitiveness of the config file. 

Please feel free to close if this is out of scope!

**Comment by koekeishiya** [comment]
> One that I think would fit right in is the way they do substitutions.

I'd like this as well, but not sure if / when it will happen.

**Comment by koekeishiya** [comment]
After further investigation, it seems like this will probably require a complete rewrite of the parser, and so is likely to be deemed out of scope.

**Comment by chrishoage** [comment]
No worries, feel free to close this if you'd like.
