### ISSUE TITLE
Remap two keys (like y and z) for any modifier key

### ISSUE THREAD

**Issue by therealmarv** [koekeishiya/khd#33]
I want to switch y and z key entirely for any modifier key (no mod, shift, cmd, .... etc.)

It would be cool to have some sort of special modifier shortcut/code which describes that I want to map two keys regardless of the modifier key pressed.

(It's first time I use khd and recognized that undo/redo needed to be mapped again for z and y).

Thanks for khd!

**Comment by koekeishiya** [comment]
Khd wasn't really built with key-remapping in mind, but as a simple way to launch some script upon a keypress.

Currently, what you want is not possible to do, however there have been other requests regarding ability to remap modifiers and such (Reference: #21).

The ability to perform key-remap might be added in the future.

**Comment by koekeishiya** [comment]
I've decided this is out of scope for Khd, see #50
