### ISSUE TITLE
How to get Umlauts pressed with khd -w (unicode issue)

### ISSUE THREAD

**Issue by therealmarv** [koekeishiya/khd#35]
This is maybe useful for other people. Maybe in longterm some more Unicode support would be great?

Use case: I wanted to Umlauts `üÜäÄöÖ` be pressed on alt + u/a/o

```
# Umlaute
alt - u             :   khd -w "ü"
alt - a             :   khd -w "ä"
alt - o             :   khd -w "ö"
alt + shift - u     :   khd -w "Ü"
alt + shift - a     :   khd -w "Ä"
alt + shift - o     :   khd -w "Ö"
```

My problem was that khd did not pressed Umlauts. I got some strange other character. After saving the khd config file as `Mac Roman` coded the Umlauts were interpreted right:

![image](https://cloud.githubusercontent.com/assets/1050582/21559829/9c294ece-ce8e-11e6-8156-5aad8ed59f4a.png)

**Comment by koekeishiya** [comment]
Reference: function responsible for identifying key-literals `https://github.com/koekeishiya/khd/blob/master/src/locale.cpp#L49`

**Comment by leemhenson** [comment]
I have a similar need. I want to map `ralt - a` to `∀`. I've tried:

```
ralt - a : khd -w "∀"
```

but it prints out `,` instead. My `khdrc` is saved with UTF-8. I am unable to save it as `Mac Roman` as that does not support the `∀` character. I can't figure out if there's a keycode I can use with `-p` instead?

**Comment by koekeishiya** [comment]
Fixed at master. Sorry about that.

**Comment by leemhenson** [comment]
v1.1.4 is working great for me now. Thanks!

**Comment by kidpixo** [comment]
@therealmarv is the solution to #93 more a good one for this issue too?

**Comment by therealmarv** [comment]
@kidpixo I don't have this problem for me personally but I also just use English and German and do not care about languages beside that.

Personal note: I stopped using khd and switched over to Hammerspoon mainly because of khd's stability issues.

**Comment by kidpixo** [comment]
Thanks, do you have a khd-ish configuration for hammerspoon to share?

For example, I cannot find how to bind simple 'switch to next/prev space' with khd.

**Comment by therealmarv** [comment]
Here is the same functionality like for my Umlaute approach in Hammerspoon lua:

https://gist.github.com/therealmarv/224515917abd072425933552b0a41be9
