### ISSUE TITLE
Swap Keys (command + tab to control + tab)

### ISSUE THREAD

**Issue by brsanthu** [koekeishiya/khd#38]
Is it possible to swap a key combination like command + tab to control + tab? Any help is appreciated.

**Comment by koekeishiya** [comment]
The following should work: `cmd - tab : khd -p "ctrl - tab"`

**Comment by brsanthu** [comment]
Added the combination but not seems to be working. Is there a log file that I can see if khd has received the event and transformed?

**Comment by koekeishiya** [comment]
From the readme:

Location of logs:
```
  stdout -> /tmp/khd.out
  stderr -> /tmp/khd.err
```
