### ISSUE TITLE
Discussion: mode keybind behavior

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/khd#39]
I have been running into a very annoying issue with modes. 

Sometimes I will have an absent minded moment and forget what "mode" I'm in. If the mode doesn't have a keybind set, it lets the keys though for the OS to handle. 

This is problematic in this situation: `cmd + alt - h` in the default `khdrc` is used to give the west window focus. `cmd + alt - h` is also OS X's "Hide all other windows" command. When in a mode that does not have `cmd + alt - h` bound, and `cmd + alt - h` is issued all other windows aside from the focused app. 

I prepose two possible solutions that are mutually exclusive: 

1. Swallow all unregistered keypresses when a non `default` mode is active. This would prevent you from typing when the mode is active, but would also prevent the situation above. 
2. Allow `default` keybindings to also trigger when in a non-`default` mode, allowing the mode keybind to supersede any conflicting `default` binding. 

I honestly don't have any preference between the two, the only goal of the change would be to prevent the frustrating situation where `cmd + alt - h` hides all other windows. 

Number 1 would make khd's modes closer to sxhkd's "chords". 
Number 2 would allow things like global navigation commands to be accessible in a mode with out having to rebind them for the mode. 

Nothing in this ticket is immediately actionable, this is simply to discuss these options to see if either of them are viable, or neither of them.

**Comment by koekeishiya** [comment]
Both options suggested here seem appropriate.
I would personally prefer the first solution.

**Comment by sunjon** [comment]
I experience the same issue. My preference would be fore the first solution too.

**Comment by chrishoage** [comment]
> I would personally prefer the first solution.

The first solution is probably the most sensible. 

Is this something you would like to (eventually) see in khd? If so I can close this and make a new ticket to track to work for when ever you end up having time.

**Comment by koekeishiya** [comment]
> Is this something you would like to (eventually) see in khd? If so I can close this and make a new ticket to track to work for when ever you end up having time.

Sure, go ahead.
