### ISSUE TITLE
khd crashes on startup after update

### ISSUE THREAD

**Issue by Feliix42** [koekeishiya/khd#41]
After updating my kwm/khd today, my `khd` daemon keeps crashing right after the start. Running `brew services list` gives me:

```
$ brew services list
Name Status  User  Plist
dbus stopped
khd  error   felix /Users/felix/Library/LaunchAgents/homebrew.mxcl.khd.plist
kwm  started felix /Users/felix/Library/LaunchAgents/homebrew.mxcl.kwm.plist
```

`/tmp/khd.out` and `.err` are empty. :/

I didn't change anything in my settings file and the khd service worked fine until I updated it. Were there any changes? Or do I have to search for the problem in `kwm`s settings?

**Comment by Feliix42** [comment]
When building from source, I get `Khd: Could not start daemon! Terminating.`.

**Comment by chrishoage** [comment]
@koekeishiya I am seeing code-signing issues with the new version of khd. I am prompted for accessibility access again when installing the new version of khd. 

I'm unsure if that has anything to do with this issue.

**Comment by dominiklohmann** [comment]
I think the old code signing certificate expired.

Go to `System Preferences > Security & Privacy > Privacy > Accessibility`, then select Khd and remove it to remove the old certificate. You should be prompted to add it again, so do that.

**Comment by Feliix42** [comment]
I was prompted again, yes. But this did not solve the problem. :/

**Comment by paulhybryant** [comment]
I have the same issue as well. The daemon cannot be started.

**Comment by koekeishiya** [comment]
> I am seeing code-signing issues with the new version of khd. I am prompted for accessibility access again when installing the new version of khd.

Uh, that seems rather odd. Khd was codesigned with the same certificate as always.
Kwm did get a new certificate and needs to given access again though.

Do note, after accepting the accessibility prompt, you need to restart the brew service.
```
brew services stop koekeishiya/khd/khd
brew services start koekeishiya/khd/khd
```

If you still have problems, is there any output in `/tmp/khd.err`, `/tmp/khd.out` ?
Which version of MacOS are you running?

**Comment by bortigel** [comment]
I had the same issue; tried `brew switch` to previous version, reinstalling, tinkering with accessibility settings and such, but nothing helped. As a last resort, I rebooted the OS and it resolved the problem.

**Comment by dominiklohmann** [comment]
> I rebooted the OS and it resolved the problem.

In that case a simple `brew services restart khd` probably would've fixed it as well.

**Comment by bortigel** [comment]
> In that case a simple brew services restart khd probably would've fixed it as well.
It didn't, I have restarted many times, only the full reboot helped. I checked with `netstat` that port 3021 wasn't blocked by anything.

**Comment by Feliix42** [comment]
After uninstalling `khd` again, rebooting (yes, only rebooting works, as @bortigel said) and installing/starting `khd` again via brew it worked. No other suggested method worked. 

I suspect that `khd` was not properly stopped before updating it. And so the Port 3021 was not used but still blocked from the old `khd` instance. But I can only speculate as I haven't looked behind the scenes of the brew update mechanisms.

**Comment by chrishoage** [comment]
Anecdotally the only troubles I had with the upgrade was the code signing. I did not require a reboot in order to upgrade, just had to reaccept khd in the accessibility pane.

**Comment by koekeishiya** [comment]
I'll consider this issue resolved.
