### ISSUE TITLE
KHD stopped working after upgrading to 1.1.2

### ISSUE THREAD

**Issue by paulhybryant** [koekeishiya/khd#43]
I have the following config in my .khdrc previous and it is working fine.
It opens a new chrome tab with ctrl-t in chrome.

lctrl - t   [Google Chrome]  : khd -p "cmd - t"

However, after upgrading to 1.1.2 it stopped working.
I have rebooted my mac and reinstalled khd and it is still not working.

From /tmp/khd.out, every time I press ctrl + t when the focus is on chrome, the following is printed:
Token_Modifier: cmd
Token_Literal: t

I tried to run khd -p "cmd - t" from iTerm2, and it printed the same thing and opens up
a new iTerm tab, which seems to indicate khd is functioning fine.

Please advice how I can debug?

Thanks!

**Comment by paulhybryant** [comment]
Also, I have another hotkey defined as follows:
lctrl - l [Google Chrome] : khd -p "cmd - l"

After pressing ctrl + l, instead of having the focus go to the chrome url input box, it triggers a shortcut I defined using automator (ctrl + cmd + l)

**Comment by koekeishiya** [comment]
Am I correct in assuming that you are running MacOS Sierra?

I'm unable to reproduce this issue, but that makes sense as I am on El Capitan.
I believe this is actually an issue caused by #40 (which was necessary for Sierra) to work at all.

**Comment by choco** [comment]
This fixes the issue for me and also keeps system shortcut working.
```
diff --git a/src/hotkey.cpp b/src/hotkey.cpp
index 4ee5d80..7242446 100644
--- a/src/hotkey.cpp
+++ b/src/hotkey.cpp
@@ -572,7 +572,21 @@ CreateAndPostKeyEvent(CGEventFlags Flags, CGKeyCode Key, bool Pressed)
 
     if(IsMacOSSierraOrNewer())
     {
-        Flags |= CGEventGetFlags(KeyEvent);
+        CGEventFlags EventFlags = CGEventGetFlags(KeyEvent);
+        EventFlags &= ~Event_Mask_Cmd;
+        EventFlags &= ~Event_Mask_LCmd;
+        EventFlags &= ~Event_Mask_RCmd;
+        EventFlags &= ~Event_Mask_Shift;
+        EventFlags &= ~Event_Mask_LShift;
+        EventFlags &= ~Event_Mask_RShift;
+        EventFlags &= ~Event_Mask_Alt;
+        EventFlags &= ~Event_Mask_LAlt;
+        EventFlags &= ~Event_Mask_RAlt;
+        EventFlags &= ~Event_Mask_Control;
+        EventFlags &= ~Event_Mask_LControl;
+        EventFlags &= ~Event_Mask_RControl;
+
+        Flags |= EventFlags;
     }
 
     CGEventSetFlags(KeyEvent, Flags);
```

**Comment by choco** [comment]
A more elegant way would be to know what modifiers were used to trigger an event and clear only those, but this also solves the issue.

**Comment by paulhybryant** [comment]
@koekeishiya yes, I am using sierra

**Comment by choco** [comment]
@koekeishiya I suppose that this also solves incompatibility of the previous change with El Capitan

**Comment by koekeishiya** [comment]
> I suppose that this also solves incompatibility of the previous change with El Capitan

I think that is the case, would any of you mind trying this patch:
https://gist.github.com/koekeishiya/c540c959dc110be15d58464a4f162b1a

**Comment by paulhybryant** [comment]
I can confirm the patch works

**Comment by koekeishiya** [comment]
> A more elegant way would be to know what modifiers were used to trigger an event and clear only those, but this also solves the issue.

Indeed that would be true, but as the `khd -p` happens in a newly created process, it has no information regarding the existing modifier state, and it would be more expensive to detect this instead of just performing a clear for every flag.

I suspect this won't be much trouble, as it should be faster to clear these flags than it was to check for the OS version.

**Comment by koekeishiya** [comment]
Patch has been applied and v1.1.3 released.
