### ISSUE TITLE
Question: Are we able to create hotkey for locking the screen?

### ISSUE THREAD

**Issue by paulhybryant** [koekeishiya/khd#44]
Are we able to create hotkey for locking the screen? It seems the power key is not available?

**Comment by dominiklohmann** [comment]
A mapping like this should do it:

```
cmd + ctrl - l : open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app
```

If you want to macOS to always require a password after invoking the screen saver, select "Immediately" in the Security & Privacy settings as shown below.

<img width="780" alt="screen shot 2017-01-13 at 01 22 01" src="https://cloud.githubusercontent.com/assets/4488655/21913784/ec17377a-d92e-11e6-84c8-43416483c409.png">

**Comment by paulhybryant** [comment]
That works perfectly! Thank you! @dominiklohmann

**Comment by dominiklohmann** [comment]
Just found an alternative that works even better... instead of `open <screensaver>`, run `pmset displaysleepnow`.

**Comment by paulhybryant** [comment]
cool~, thanks!
