### ISSUE TITLE
Swallow unregistered keypresses when non-default mode active

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/khd#47]
After coming to a consensus in #39 it was decided that non-default modes should swallow keypresses that are not registered to that mode. 

This would require the user to exit the mode before regular keypresses would be registered in other applications. 

Due to the nature of this change, it might be a good idea to include it in the next major version (2.x).

**Comment by koekeishiya** [comment]
I suppose this could be a config option, enabled by default.

**Comment by koekeishiya** [comment]
This can be set by adding the following to the config file
```
khd void_unlisted_bind on | off
```

Default value is currently `off`.
This is likely to be enabled by default in the next release version.
If that is the case, it will be marked as a major version change.

**Comment by koekeishiya** [comment]
This is enabled by default in the latest release.
