### ISSUE TITLE
support: using home/end keys?

### ISSUE THREAD

**Issue by gcbw** [koekeishiya/khd#54]
i can't find how to use the home/end keys of a external keyboard.

looked at the sample file and https://github.com/koekeishiya/khd/issues/1 and still have no idea what's their keycode.

i want to map home to cmd+left arrow, and end to cmd+right arrow.

I tried simply using 73/74 as in:
```
# sane home/end keys
# home
73    :   khd -p "- left"
# end
74    :   khd -p "- right"
```
(using left/right because i wanted to copy something from another example to make sure the problem is only the keycodes)

**Comment by koekeishiya** [comment]
I do not have an external keyboard to test this right now, but if I remember correctly, home is 0x73 and end is 0x77. These should exist as literals, will push a commit that fixes this soon.

In the meantime, adding the following lines in your config file should do it
```
- 0x73 : khd -p "cmd - left"
- 0x77 : khd -p "cmd - right"
```

**Comment by gcbw** [comment]
thanks! tried adding the 0x but still nothing after `brew services restart koekeishiya/formulae/khd`

**Comment by koekeishiya** [comment]
I added a binding between literals and the actual keycode specified by the header file from Apple, however, I actually have no idea if these are keys that we can detect.

I'm afraid I can't do much more for quite some time, as I don't have access to an external keyboard.
Hopefully someone else can help debug this, after the bindings provided in the latest commit.

You can use the following literals when compiled from master: `home`, `end`, `pageup`, `pagedown`, `help`

**Comment by dominiklohmann** [comment]
My keyboard doesn't have a `help` key, but the others work just fine for me.

**Comment by gcbw** [comment]
I had a dangling char on my commented out conf file at the end. Only spotted it when running khd as root and no arguments. It never complained when starting the service, even though it was crashing...

using https://github.com/koekeishiya/khd/issues/54#issuecomment-275210567 solves my problems perfectly! thanks

**Comment by koekeishiya** [comment]
> It never complained when starting the service, even though it was crashing...

It should write error messages to `/tmp/khd.err`, but it does not give the user "visual" feedback when managed by launchd.
 
I could probably have it create a popup-box on error, but I feel like that would be rather intrusive.

Closing this as resolved.
