### ISSUE TITLE
How to start brew services with `-c path/to/custom/config` parameter?

### ISSUE THREAD

**Issue by Kutsan** [koekeishiya/khd#56]
`brew services start khd -c path/to/custom/config` did fail because probably brew services doesn't take arguments. How I start khd with my custom config location which is not in my root home directory. README.md says `khd -c path/to/custom/config` but this is temp solution I think, can't run as service.

**Comment by dominiklohmann** [comment]
You can edit `~/Library/LaunchAgents/homebrew.mxcl.khd.plist` accordingly.

**Comment by Kutsan** [comment]
Thanks but when I restart khd service, this .plist file will overridden. And because of that I can't set parameters. What should I do?

**Comment by dominiklohmann** [comment]
Instead of loading the plist via `brew services start khd`, launch it with `launchctl` directly.

You could for example create your own .plist file in that directory and then run `launchctl load ~/Library/LaunchAgents/<filename>.plist` to load it.

**Comment by koekeishiya** [comment]
As dominiklohmann stated, you need to create your own `.plist` file to do this.

**Comment by Kutsan** [comment]
Thanks!
