### ISSUE TITLE
Modifier only bindings

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/khd#6]
See title

**Comment by koekeishiya** [comment]
Modifier only bindings trigger if a `modifier pressed -> modifier released` happens within a 100ms timeframe. 

The reason for this is to keep it from interfering with keypresses that require that modifier to be down.

**Comment by 0x3333** [comment]
Well, I tested it and it kind of work.

This 100ms is too fast. If you bind `cmd + alt + shift` 100ms is impractical.

Is that possible to remove or change this timer?

**Comment by koekeishiya** [comment]
Should probably add an option to set the timer in the config file.

In the meantime, you can edit the timeout at `src/hotkey.cpp:381`.
Currently set to `0.1` (seconds)

**Comment by koekeishiya** [comment]
You can now use the option `khd mod_trigger_timeout <seconds>` to change this timer.
