### ISSUE TITLE
Remap shortcut twice 

### ISSUE THREAD

**Issue by bolshakov** [koekeishiya/khd#61]
I have the following config:

```
cmd - j : khd -p "cmd - c"
cmd - c : khd -p "- up" 
```

I expect:

* pressing `cmd + j` produces `cmd + c`
* pressing `cmd + c` produces `up`

But actually both combinations `cmd + j` and `cmd + c` produces `up`.

**Comment by koekeishiya** [comment]
The combination "cmd - c" event generated by "cmd - j" triggers your "cmd - c" bind, causing "- up" to be the end result.

**khd** is not really meant for remapping, but you can achieve the above with some tricky commands like below:

```
khd void_unlisted_bind off
cmd - j : khd -e "mode activate remap"; khd -p "cmd - c"
remap + cmd - c -> : khd -e "mode activate default"
cmd - c : khd -p "- up"
```

**Comment by bolshakov** [comment]
Thanks for so fast response! I tried that tricky snippet and it does not help. Pressing `cmd - c` still cause `- up` :(

**Comment by koekeishiya** [comment]
It works perfectly for me.

Tested with an empty config containing nothing but this:
```
cmd - j : khd -e "mode activate remap";\
          khd -p "cmd - c";\
          khd -e "mode activate default"
remap + cmd - c -> : true
cmd - c : khd -p "- up"
```

Are there any errors reported in `/tmp/khd.err` or `tmp/khd.out` ?

**Comment by bolshakov** [comment]
I've just copy-pasted exactly the same config, restarted khd and pressed `cmd - c` once. 

```
> cat /tmp/khd.out
Token_Modifier: cmd
Token_Literal: c
> cat /tmp/khd.err
```

My input cursor moved up.

**Comment by koekeishiya** [comment]
> pressed cmd - c once.

> My input cursor moved up.

That's the expected behaviour.

> I expect:

>    pressing cmd + j produces cmd + c
   pressing cmd + c produces up

pressing `cmd + j` will perform a "normal" `cmd + c`.
