### ISSUE TITLE
How to remap fn to ctrl

### ISSUE THREAD

**Issue by ndrizza** [koekeishiya/khd#65]
How would you remap the 'fn' key to 'ctrl'?

I've seen that fn may be installed as a modifier - how do you remap modifier keys?

**Comment by ndrizza** [comment]
I've found this modifier-only remap in the examples:
left cmd      -> {    right cmd     -> }
however, 
fn                -> { ctrl ->}
doesn't work

**Comment by chrishoage** [comment]
On key remapping: https://github.com/koekeishiya/khd/issues/50

**Comment by ndrizza** [comment]
Alright, thank you!

**Comment by koekeishiya** [comment]
Modifiers can't be remapped with Khd. Use Karabiner-elements for this.
