### ISSUE TITLE
How to emit volume up/down keys?

### ISSUE THREAD

**Issue by esad** [koekeishiya/khd#69]
I'm trying to make my regular F11/F12 keys control the volume. Any idea how to achieve this?

**Comment by koekeishiya** [comment]
Uh, you can control the volume using applescript, and then execute said applescript when hitting the f11 / f12 keys.

Something like this: https://coderwall.com/p/22p0ja/set-get-osx-volume-mute-from-the-command-line 

You probably have to read up on applescript syntax if you want to get the current volume and add some amount to it, for incremental changes.

**Comment by esad** [comment]
So there's no keycode we could emulate for system to register volume up/down presses?

**Comment by esad** [comment]
I've found https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-86.1/IOHIDSystem/IOKit/hidsystem/ev_keymap.h -- do you think it's out of scope for khd to have builtin support for sending these events?

**Comment by koekeishiya** [comment]
Implemented, see https://github.com/koekeishiya/khd/issues/1#issuecomment-247729363 for literals

**Comment by esad** [comment]
@koekeishiya Wow that was quick. Already tried the new release and it works great!
