### ISSUE TITLE
Input latency of over a second for every key press

### ISSUE THREAD

**Issue by nevyn** [koekeishiya/khd#71]
When using default example kwm and khd config files, every key press takes about a second before khd interprets it. For example, when pressing ctrl-f, nothing happens until one second later, after which the border changes color and switcher mode is activated. Typing during this delay yields keyboard input into the frontmost application (and not delayed input into khd or something like that).

`/tmp/khd.err` spams this twice for every time I press a key that khd interprets:

```
set: Warning: $PATH entry "/Library/Frameworks/Mono.framework/Commands /Users/nevyn/Library/Android/sdk/platform-tools /Users/nevyn/Dev/depot_tools /Users/nevyn/bin $PATH /usr/local/Cellar/khd/2.2.2/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin" is not valid (No such file or directory)
```

It is logged _after_ the one-second delay.

Is it an incompatibility with the `fish` shell or something?

**Comment by koekeishiya** [comment]
See #23
