### ISSUE TITLE
how to start command line tool with shortcuts

### ISSUE THREAD

**Issue by mingsu** [koekeishiya/khd#73]
I know how to start iTerm with shortcuts according to the manual, with this:

 `cmd + return   :  open -na /Application/iTerm.app`

But I don't know how to start other CLI tools likes `ranger` and `mutt`

When I was in `xmonad` within `linux`,

I can setup something like:
`.... : xterm -e ranger`
`.... : xterm -e mutt`

**Comment by chrishoage** [comment]
This isn't really a problem with khd, you'd need to figure out how to launch iTerm with a command. Some quick googling shows me that apple script might be a solution. 

in any case khd is just executing a command. So you'd need to figure out how to launch iTerm with the command you want.

**Comment by koekeishiya** [comment]
The **open** tool provided with MacOS allows you to specify `--args <argument>`

To run **ranger** inside iTerm2, you can do

```... : open /Applications/iTerm.app --args ranger```

The **.app** is also just a folder structure enforced by Apple, instead of going through the **open** too, you can run the binary directly like so (name of binary may differ, same concept applies):
```
... : ./Applications/iTerm.app/Contents/MacOS/iterm argument
```

**Comment by dominiklohmann** [comment]
Using `open -n` is wasting resources since it loads a new instance of the application instead of simply creating a new window. For iTerm2 2.9+ the following AppleScript will open a new window and optionally run a command in it:

```
<shortcut> : osascript -e 'tell application "iTerm2" to create window with default profile'
<shortcut> : osascript -e 'tell application "iTerm2" to create window with default profile command "vim"'
```

**Comment by mingsu** [comment]
@chrishoage I am sorry that I understand this is not a issue of khd, I just knew to macos, and have spend lots of time to adapt the new system.

@dominiklohmann I really appreciate your solution. Save me lots of time.

**Comment by mingsu** [comment]
@dominiklohmann 
when i use your code shown below, one issue I have is **it always start two iTerm when no iTerm has been started**, but it works fine if there were at least iTerm runing.

> <shortcut> : osascript -e 'tell application "iTerm2" to create window with default profile'

**Comment by dominiklohmann** [comment]
In the iTerm settings under `General > Startup` select `Don't open any windows` to fix that issue.

**Comment by mingsu** [comment]
@dominiklohmann Great!
