### ISSUE TITLE
Replace kwm integration layer with a more general one

### ISSUE THREAD

**Issue by choco** [koekeishiya/khd#77]
Since chunkwm is coming along pretty nicely, it would be cool to add support for it. But instead of adding other specific code I was thinking of adding a more general integration layer.
- Remove kwm specific code
- Add to mode structure 2 more fields:
   1. **onEnterCommand** : when entering a mode
   2. **onExitCommand** : when quitting a mode
 
  and remove the colour field.
- Refactor remaining code to suite new structure and functionality.

Thoughts?

**Comment by koekeishiya** [comment]
Being able to generalize this would be a good change indeed

**Comment by koekeishiya** [comment]
I think the onExitCommand is redundant, as we always enter a new mode upon exit.

**Comment by koekeishiya** [comment]
`khd kwm on` and `kwm` specific code has been removed.
`khd mode <mode> color` property has been removed.
`khd mode <mode> on_enter <command> has been added.

before:
```
khd kwm on
khd mode prefix color 0xffff0000
```
after:
```
khd mode prefix on_enter kwmc config border focused color 0xffff0000
```

replace `kwmc ..` command with whatever, e.g: `chunkc <something>` or however we end up controlling borders in that system.
