### ISSUE TITLE
Expected token of type 'Token_Command' after symbols

### ISSUE THREAD

**Issue by sthtodo** [koekeishiya/khd#78]
MacOS 10.12.5

/tmp/khd.err outputs this
Line#4: Expected token of type 'Token_Command' after symbols!

.khdrc
`khd kwm on

cmd + alt + ctrl - q     :   kwmc quit`

**Comment by dominiklohmann** [comment]
The kwm integration has been removed, see https://github.com/koekeishiya/khd/issues/77#issuecomment-309242995 for what changed.

**Comment by sthtodo** [comment]
@dominiklohmann Thanks to let me know. in kwm example config still use this.

**Comment by dominiklohmann** [comment]
Actually the khd example config has been updated in time for the 3.0.0 release, it's just that the example config that shipped with 2.x releases does not work anymore.

**Comment by koekeishiya** [comment]
I think he was referring to the khdrc inside the kwm repository. This is indeed outdated, but I can't be bothered maintaining that anymore. Kwm will be deprecated, hopefully by the end of this month, and an official Alpha release for chunkwm will be ready.

**Comment by sthtodo** [comment]
Thanks for all the information.
