### ISSUE TITLE
symbol and f1-f15 tokens problem

### ISSUE THREAD

**Issue by wxmtech** [koekeishiya/khd#79]
I've been working on this config for a while, I tried to double quote the symbol keys, sometimes it works as tokens, but sometimes it is not. For f1-f15, it never works. I tried to use the hex code to refer to the keys, it is working, wondering if this is the only way that can make the symbol keys and fn keys working, since it is not that intuitive to review the config file for "beginners".

**Comment by koekeishiya** [comment]
Uh, just doing `cmd - f1` etc should work to bind the f1-12 keys.

**Comment by wxmtech** [comment]
Thanks a lot, this works now, the reason I post it is cuz previously, I got errors like:

> Line#40: Invalid format for key literal: _
> Line#41: Expected token of type 'Token_Command' after symbols!

which confuses me a lo, and when "khd -e "reload"" or "brew services restart khd", sometimes it is still being a little strange.
