### ISSUE TITLE
Please support lcmd + rcmd key triggers

### ISSUE THREAD

**Issue by kconner** [koekeishiya/khd#8]
In Karabiner, before Sierra, I used `left command + ESDF` for arrow keys. So I could do things like:

1. `left command - E` -> `up`
2. `left command + shift + alt` -> `shift + alt - up`
3. `left command + right command - E` -> `command - up`

My .khdrc attempts to produce that behavior with khd: https://gist.github.com/kconner/9c7d3c89d187e091a65b67ec398c5e0a

Key combinations like cases 1 and 2 do what I expect in khd. Case 3 does not work. It it interpreted like case 1.

Is this possible? Can you detect both command keys being held down using Quartz Event Services?

I'm using khd 1.0.1 from `brew` on macOS 10.12 Sierra 16A319.

**Comment by koekeishiya** [comment]
Requires some tweaking, but yes, I believe that should be possible.

**Comment by koekeishiya** [comment]
I tested simple combinations such as
```
lcmd - o
rcmd - o
lcmd + rcmd - o
```
and that works fine now. I have not tested more complex ones as shown in your gist file, but hopefully they do work fine.

It would be nice if you could build from master and see if it works as suggested, before a new release is made.

**Comment by kconner** [comment]
I'll try this out soon, thank you!

**Comment by spenrose** [comment]
I added a pull to allow installing from master with brew. 

https://github.com/koekeishiya/homebrew-khd/pull/1

**Comment by kconner** [comment]
That worked for me, with all my different key combinations.

**Comment by kconner** [comment]
For anyone who needs to replicate this, I had to:

- clone this repository
- `make`
- replace /usr/local/bin/khd with a symlink to the repository's bin/khd
- remove `khd` from System Preferences > Security > Privacy > Accessibility, since I was replacing the executable
- `brew services restart khd`
- approve `khd` in System Preferences > Security > Privacy > Accessibility
