### ISSUE TITLE
Sometimes bindings don't trigger the OS

### ISSUE THREAD

**Issue by darvelo** [koekeishiya/khd#81]
I have a few bindings in a khd `switcher` mode that map to OSX bindings that switch spaces, e.g.:

* `switcher - w` maps to  `ctrl + alt - left` in OSX: switch to space to the left of current space
* `switcher - 2` maps to `ctrl + alt - 2`: switch to space 2
* `switcher - tab` maps to `ctrl + alt - $(chunkc get _last_active_desktop)`

The issue is that sometimes these bindings don't switch spaces, and the screen stays on the same space it was on before the khd binding was pressed. I'm not sure how to diagnose what's causing this to happen, but it happens pretty frequently. Using the native OSX bindings seems to work fine. I'm open to suggestions on how I can help figure out the cause.

**Comment by koekeishiya** [comment]
I think this could be related to the delay specified [here](https://github.com/koekeishiya/khd/blob/master/src/emulate.m#L87)

There has to be a certain delay between key-down and key-up events. It could be that the delay needs to be higher on your machine. Not sure yet why this delay is necessary and how long it has to be. But removing the delay (or making it any lower) gives me the same problem.

Can you try to increase the delay and compile from source to see if it has any impact on the problem?

**Comment by darvelo** [comment]
Changing that delay to `3000`, `14000`, and `24000` didn't seem to have an effect.. The bright side is that I've found a way to reproduce it every time. I have the following hotkeys:

```
switcher - w         :   khd -p "ctrl + alt - left"
switcher - e         :   khd -p "ctrl + alt - right"
switcher - tab          :   khd -p "ctrl + alt - $(chunkc get _last_active_desktop)" ; khd -e "mode activate default"
switcher - 1            :   khd -p "ctrl + alt - 1" ; khd -e "mode activate default"
...
```

If I use `switcher - w` (or `e`) to change space, then wait any amount of time and use `switcher - tab` or `switcher - {number}`, the space won't change to the desired space from the second  hotkey. Interestingly, while typing this comment I tested again and found that a number was being typed into this text box when I used the second hotkey, possibly meaning that the keypress is being sent to macOS without the modifier keys.

**Comment by koekeishiya** [comment]
@darvelo Thanks, I'm able to reproduce.

It appears that the *number* key gets "stuck" for some reason.

I reproduced above by running the `khd -p` commands directly in two terminals (1 for each space).

Terminal on Space 1: `khd -p "cmd + alt - c"` (which is my next-space bind)
Terminal on Space 2: `khd -p "cmd + alt - $(chunkc get _last_active_desktop"`

After some time, `khd -p "cmd + alt - $(chunkc get _last_active_desktop"` will start to fail.
If i manually tap the `1` key (which is the value of _last_active_desktop), so it is pressed -> released,
the command will work again. I did not touch the modifiers on my keyboard in this case.

This is similar to the problem I mentioned above IIRC.

**Comment by choco** [comment]
Sorry I don't have time to personally debug this, but a good starting point would be to dump out the Flags of the events and see if they differ from the one we output :/

**Comment by darvelo** [comment]
Strangely, I just switched over a 2015 MacBook that never experienced this issue, from `kwm` to `chunkwm` and from `khd 2.0.0` to `khd 3.0.0`, and I'm experiencing this issue as consistently as the newer 2016 MacBook I tested with originally.

**Comment by koekeishiya** [comment]
If you are still in need of a way to simulate keypresses, take a look at: https://github.com/koekeishiya/qes

The way I've done it there actually works, compared to the implementation in **khd**.
It uses the old method discovered by choco some time ago, but was seemingly removed in *Sierra*.
It is back and working in *High Sierra* for whatever reason, and does not have this issue.

**Comment by darvelo** [comment]
@koekeishiya `qes` works! 🎉 Thank you for consistently being so supportive to the community of users that choose to make your software a part of their daily lives. It's really appreciated, and honestly I wouldn't mind donating to reward your continuous effort over the years.
