### ISSUE TITLE
Remapping keys

### ISSUE THREAD

**Issue by carymrobbins** [koekeishiya/khd#82]
I have a few questions about remapping keys.  Note that I am primarily using this in conjunction with [chunkwm](https://github.com/koekeishiya/chunkwm).  I've asked some of these in the `##kwm` channel in freenode; however, I have no idea if that's the appropriate place so I'm now coming here.

-----------------------------------

**1.** Using the following in my .khdrc, but it doesn't seem to work (as in, doesn't seem to trigger anything when I press `ctl-t`)

```
ctl - t : khd -p "cmd - t"
```

Ideally this would just remap `ctl-t` to `cmd-t`

------------------------------------

**2.** Is it possible to remap to bindings that already exist in khd?  For instance, I'd like to have this binding -

```
cmd - w  : chunkc tiling::monitor -f 3
```

But then also have

```
ctl - w : khd -p "cmd - w"
```

I'm not sure if this would even work in theory (due to some sort of key binding loop), but that doesn't seem to do anything either; in fact, none of the `khd -p` commands seem to work.

------------------------------------

**3.** I am currently using Karabiner-Elements to remap `fn` to `ctl` and `ctl` to `fn`; is it possible to do this with khd?  Since Karabiner-Elements can pull it off, it also seems like this may prove that key binding loops are avoidable (as I mentioned in point 2), I'm just not sure how to pull it off.

**Comment by chrishoage** [comment]
Key remapping is not a supported feature of khd: https://github.com/koekeishiya/khd/issues/50

**Comment by carymrobbins** [comment]
What is the difference between key remapping and `khd -p` ?

**Comment by chrishoage** [comment]
`khd -p` triggers key strokes. It's more an auto-type than key-remaping. 

From the linked issue:

> Using khd -p to perform 'fake key-remapping' can be done to some extent, but this was never the intention of the feature

**Comment by koekeishiya** [comment]
As chrishoage said, we do not do keymapping, but we can emit keystrokes.

Your particular case should both work, but you likely need `khd void_unlisted_bind off`.

```
# when 'default' mode is NOT active, any key-combination that
# does not correspond to a valid bind will be suppressed.
# this is enabled by default, and must be explicitly set to 'off'.
khd void_unlisted_bind off
```

**Comment by koekeishiya** [comment]
To expand on the previous answer. Even if you could to case 2 in *khd*, I would not recommend doing so, because it will incur noticable delay. `khd -p` in general is not amazingly fast, due to macOS API constraints.

**Comment by carymrobbins** [comment]
Karabiner-Elements is certainly the best way to pull this off.  Thanks!
