### ISSUE TITLE
Any tests and reports if this works in macOS High Sierra 10.13 ?

### ISSUE THREAD

**Issue by therealmarv** [koekeishiya/khd#87]
Would be nice to know (maybe in readme?) if this works in macOS High Sierra because it will be released on September 25th and I'm only checking if all my critical software works there.

Thanks a lot for khd!

**Comment by koekeishiya** [comment]
I have no reason to suspect that khd will break on High Sierra. That said, I have not personally tested it, as I'm waiting to the official release before upgrading to High Sierra (as I only have one mac that I prefer to keep stable).

On the off-chance that it does not work on High Sierra (assuming that would also break *skhd*), I'll get a working version up fairly quickly,

**Comment by dominiklohmann** [comment]
Both skhd and khd work on the GM, just tested it.

**Comment by koekeishiya** [comment]
Confirmed working on High Sierra. Closing this.
