### ISSUE TITLE
Feature request: Running a bash command upon some key combination

### ISSUE THREAD

**Issue by ndrizza** [koekeishiya/khd#89]
It would be nice to have that.

**Comment by chrishoage** [comment]
Unless I'm misunderstanding this already exists 

https://github.com/koekeishiya/khd/blob/4765ae0b4c7d4ca56319dc92ff54393cd9e03fbc/examples/khdrc#L163-L164

**Comment by dominiklohmann** [comment]
What you are requesting is quite literally the only thing khd does.

If you define a hotkey in your `$HOME/.khdrc`, everything to the right side of the colon is run through your `$SHELL`, which usually is `bash`. 

An example for a more complicated command would be something like this (using `repeat`, a build-in command from `zsh`, which is my `$SHELL`). 
```zsh
# Save current desktop mode, set mode to monocle, wait, 
#   close all windows, set mode to old mode
# This is a useless command for demonstration purposes
cmd + ctrl - w : $MODE=chunkc tiling::query --desktop mode \
              && chunkc tiling::desktop --layout monocle \
              && sleep 0.5 \
              && repeat $(chunkc tiling::query --desktop windows | wc -l) { \
                     chunkc tiling::window --close \
                  && sleep 0.1 } \
              && chunkc tiling::desktop --layout $MODE
```

**Comment by ndrizza** [comment]
Thanks for the examples! Now I see how it works.
