### ISSUE TITLE
khd not working using launchd & nix-darwin

### ISSUE THREAD

**Issue by gbuisson** [koekeishiya/khd#96]
Hi,

I'm trying to setup khd using nix-darwin, the service definition is located here:

https://github.com/LnL7/nix-darwin/blob/master/modules/services/khd/default.nix

it looks to be generating a .plist similar to the one from brew, except, the paths are changed
I only added some lines to allow logging:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/nix/store/4n1s253as4lsifc4x3w8gc73blv9ml9l-khd-2.1.1/bin:/nix/store/qv196n0crvk8gkiga6kyzlxiryazi07p-chunkwm-core-0.2.36/bin:$HOME/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>org.nixos.khd</string>
	<key>ProcessType</key>
	<string>Interactive</string>
	<key>ProgramArguments</key>
	<array>
		<string>/nix/store/4n1s253as4lsifc4x3w8gc73blv9ml9l-khd-2.1.1/bin/khd</string>
		<string>-c</string>
		<string>/etc/khdrc</string>
	</array>
	<key>Sockets</key>
	<dict>
		<key>Listeners</key>
		<dict>
			<key>SockFamily</key>
			<string>IPv4</string>
			<key>SockServiceName</key>
			<string>3021</string>
			<key>SockType</key>
			<string>dgram</string>
		</dict>
	</dict>
</dict>
</plist>
```
what happens is that, I can launch khd manually from a terminal and everythig works as expected, however with the launchd setup, it looks like khd restarts and prints the config every time I hit a key shortcut, the keypress is captured, but nothing happens like it's segfaulting somehow or something.

Do you have any clue ?

**Comment by LnL7** [comment]
Try debugging the service to figure out what's going on, this will send the output of the service to your current terminal.

```
sudo launchctl debug gui/$UID/org.nixos.khd --stdout --stderr
sudo launchctl kickstart -k gui/$UID/org.nixos.khd
```

**Comment by gbuisson** [comment]
@LnL7 thank you, I eventually figured that it was an issue with my shell configuration, everything works as expected now
